# Generated by Django 4.0.5 on 2023-02-08 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentorapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landlord',
            name='category',
        ),
    ]
