# Generated by Django 4.0.5 on 2023-02-08 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentorapp', '0002_remove_landlord_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='size',
        ),
    ]
