# Generated by Django 4.0.5 on 2023-02-08 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentorapp', '0004_remove_property_bathroom_remove_property_bedroom_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='description',
        ),
        migrations.RemoveField(
            model_name='property',
            name='imageOne',
        ),
        migrations.RemoveField(
            model_name='property',
            name='imageTwo',
        ),
    ]
